baseURL = "http://example.org/"
languageCode = "en-us"
title = "About me"
theme = "m10c"

[params]
  author = "Angad Sharma"
  description = "Noob is just a state of mind"
  [[params.social]]
    name = "github"
    url = "https://github.com/L04DB4L4NCER"
  [[params.social]]
    name = "twitter"
    url = ""
	[[params.social]]
		name = "linkedIn"
		url = "https://linkedin.com/in/angad-sharma-07bb38122/"

